name: Continuous Integration

on:
  push:
    branches: "ci-config"
  pull_request:
    branches: "ci-config"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 19.x
          cache: "npm"
      - run: npm ci
      - run: npm install
      - run: npm run build
      - run: npm test
